### ISSUE TITLE
pypi / conda package 

### ISSUE THREAD

**Issue by haesleinhuepf** [danifranco/BiaPy#29]
Hi @danifranco and @iarganda ,

BiaPy looks fantastic. Congratulations!

I was just wondering if there are any plans to make the installation more easy/reproducible by uploading biapy to pypi and / or conda-forge?

* https://realpython.com/pypi-publish-python-package/#configure-your-package
* https://blog.gishub.org/how-to-publish-a-python-package-on-conda-forge

At the moment, the installation instructions mention to download the source `git clone https://github.com/danifranco/BiaPy.git` and then install it using `pip install --editable .` Thus, if I download it today and next year, I might retrieve different code. This could potentially break my downstream analysis. If I could `pip install biapy==3.0` I would in both cases retrieve the same code.

I'd be happy to actively support you with this. In case you need assistance, just let me know!

Best,
Robert

**Comment by danifranco** [comment]
Hello Robert!

Thank you so much for your words, we really appreciate your support.

You're right, we need to do this as soon as possible. I will post here once it's done ;)

Best,

Dani

**Comment by danifranco** [comment]
Hi,

It's done! You can find it here: https://pypi.org/project/biapy/ . It was my first time doing it, so maybe something is wrong. I had a few problems doing it. Seems that in PyPI you can not change the description once the package is built so the first time I did it the ``README.md`` of my project was not rendered correctly under PyPI. After changing it in Github seems that you need to resubmit another version of the package, you can not use the same version or "refresh" the description somehow... So, I removed the first project in PyPI and re-uploaded BiaPy as ``3.1``version instead of ``3.1.0``, which was the first I did. Following versions will match the ones in Github. 

Feel free to close the issue and thank you so much again! 

Best,

Dani
